version: '3.1'
 
services:
 
  main:
    image: aabhassinha/jenkins-v1.1
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    restart: always

 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
